package com.swright.craftynudgev2.models

import kotlin.random.Random

class Theme {

    val themes: List<String> = listOf(
        "Happiness",
        "Beauty",
        "Sleep",
        "Garden",
        "Imagination",
        "Secret",
        "Give",
        "Thankful",
        "Kindness",
        "Inside",
        "Outside",
        "Jump",
        "Friendship",
        "Love",
        "Fire",
        "Light",
        "Darkness",
        "Dream",
        "Believe",
        "Hope",
        "Faith",
        "Focus",
        "Clean",
        "Angry",
        "Work",
        "Music",
        "Stars",
        "Mystery",
        "Envelope",
        "Book",
        "Dare",
        "Choose",
        "Beach",
        "Forgiveness",
        "Disaster",
        "Dance",
        "Mistake",
        "New",
        "Yes",
        "Path",
        "Horizon",
        "Mountain",
        "River",
        "Open",
        "Heart",
        "Soul",
        "Tear",
        "Spiral",
        "Up",
        "Go",
        "Be",
        "Seek",
        "Learn",
        "Balance",
        "Grow",
        "Strength",
        "Seek",
        "Passion",
        "Move",
        "Today",
        "Awaken",
        "Angels",
        "Laughter",
        "Listening",
        "Pause",
        "Peace",
        "Relax",
        "Space",
        "Wisdom",
        "Difference",
        "Begin",
        "Time",
        "Brave",
        "Breathe",
        "Childhood",
        "Discovery",
        "Mind",
        "Energy",
        "Flower",
        "Health",
        "Harmony",
        "Recovery",
        "Stand",
        "Nowhere",
        "Soar",
        "Skip",
        "Fresh",
        "Delicious",
        "Power",
        "Complete",
        "Grace",
        "Legend",
        "Ecstasy",
        "Hug",
        "Proud",
        "Simple",
        "Machine",
        "Victory",
        "Vibrancy",
        "Leadership",
        "Alive",
        "Bloom",
        "Fame",
        "Enormous",
        "Independent",
        "Unique",
        "Metamorphosis",
        "Silence",
        "Tranquility",
        "Project",
        "Smile",
        "Miracle",
        "Amazing",
        "Game",
        "Connected",
        "Muse",
        "Dazzle",
        "Determination",
        "Free",
        "Help",
        "Intuition",
        "Smart",
        "Sweet",
        "Honesty",
        "Useful",
        "Safety",
        "Ready",
        "Vision",
        "Cycle",
        "Discipline",
        "Promise",
        "Patience",
        "Destiny",
        "Rejuvenate",
        "Shine",
        "Talk",
        "Stress",
        "Missing",
        "Age",
        "Success",
        "Motivation",
        "Family",
        "Loneliness",
        "Experience",
        "Future",
        "Vintage",
        "Wings",
        "Letter",
        "Wandering",
        "Factory",
        "Rainbow",
        "Ask",
        "Self",
        "Locket",
        "Home",
        "Cloud",
        "Hunger",
        "Possibilities",
        "Boredom",
        "Innocence",
        "Charge",
        "Rhythm",
        "Date",
        "Consequence",
        "Prescription",
        "Goals",
        "Lost",
        "Found",
        "Cry",
        "Parade",
        "Party",
        "Ice",
        "Dragon",
        "Alarm",
        "Understanding",
        "Uncomfortable",
        "Serious",
        "Opposites",
        "Playful",
        "Attention",
        "Caring",
        "Hero",
        "Lace",
        "Clue",
        "Ideas",
        "Junk",
        "Collection",
        "Radio",
        "Interview",
        "Zoom",
        "Puzzle",
        "Landscape",
        "Advice",
        "Memories",
        "Communication",
        "Compassion",
        "Universe",
        "Loyalty",
        "Sharing",
        "Travel",
        "Voices",
        "Sidewalk",
        "Tree",
        "Story",
        "Why",
        "Maybe",
        "Antique",
        "Action",
        "Culture",
        "Fuel",
        "Desire",
        "Weather",
        "Directions",
        "List",
        "Ride",
        "Wish",
        "Breakfast",
        "Touch",
        "Sadness",
        "Comfort",
        "Circle",
        "Reflection",
        "Optimism",
        "Anxiety",
        "Shadow",
        "Spirit",
        "Stretch",
        "Challenge",
        "Five",
        "Messy",
        "Adventure",
        "Fun",
        "Surprise",
        "Illusion",
        "Mischief",
        "Shy",
        "Lesson",
        "Whisper",
        "Fight",
        "Castle",
        "Protect",
        "Shop",
        "Wheel",
        "Pieces",
        "Leaves",
        "Fool",
        "Productivity",
        "Overcome",
        "Encouragement",
        "Watch",
        "Lighthouse",
        "Mild",
        "Mouth",
        "Rare",
        "Target",
        "Boat",
        "Box",
        "Grief",
        "Heavy",
        "Zeal",
        "Color",
        "Brilliance",
        "Enthusiastic",
        "Approval",
        "Enchanting",
        "Attraction",
        "Photograph",
        "Waterfall",
        "Moment",
        "Paradise",
        "Parachute",
        "Social",
        "Zingy",
        "Number",
        "Little",
        "Sound",
        "Reach",
        "Money",
        "Staircase",
        "Lemon",
        "Wood",
        "Try",
        "You",
        "Quote",
        "Weakness",
        "Bridge",
        "Building",
        "Clothes",
        "Prepare",
        "Teach",
        "Window",
        "Drive",
        "Middle",
        "Microphone",
        "Definition",
        "Shout",
        "Catch",
        "Release",
        "Balloons",
        "Sharp",
        "Crowd",
        "Cute",
        "Cheery",
        "Glow",
        "Apple",
        "Pictures",
        "Swing",
        "Wave",
        "Joke",
        "Cope",
        "Accomplish",
        "Special",
        "Neighborhood",
        "Wonderful",
        "Service",
        "Calling",
        "Magic",
        "Spontaneous",
        "Fluffy",
        "Organic",
        "Silly",
        "Thunderstorm",
        "Toys",
        "Butterfly",
        "Buzz",
        "Vine",
        "Shock",
        "Enjoy",
        "Craving",
        "Respect",
        "Abstract",
        "Rainbow",
        "Train",
        "Invention",
        "Perspective",
        "Genius",
        "Circus",
        "Ball",
        "Crystal",
        "Fairy",
        "Cup",
        "Reality",
        "Forget",
        "Priorities",
        "Journey",
        "Hands",
        "Shoes",
        "Television",
        "Newspaper",
        "Radiance",
        "Hidden",
        "Fright",
        "Climb",
        "Guess",
        "Pretend",
        "Turn",
        "Shatter",
        "Together",
        "Adapt",
        "Keep",
        "Closed",
        "Embrace",
        "Blessing",
        "Block",
        "Pizzazz",
        "Breakthrough",
        "Curiosity",
        "Distance",
        "Zen",
        "Balloon",
        "Birthday card",
        "Birthday hat",
        "Birthday cake",
        "Bow",
        "Biscuit",
        "Candy",
        "Chocolate",
        "Ice cream bar",
        "Candle",
        "Fruit",
        "Confetti",
        "Gift",
        "Streamer",
        "Clown",
        "Gift tag",
        "Horn",
        "Popcorn",
        "Cupcake",
        "Chips (UK)/ French fries (US)",
        "Soda",
        "Ice cream sundae",
        "Candy cane",
        "Bell",
        "Bauble/ Christmas ornament",
        "Candle",
        "Bow",
        "Holly",
        "Gift",
        "Poinsettia",
        "Wreath",
        "Garland",
        "Light",
        "Candy",
        "Stockings",
        "Gingerbread man",
        "Snow globe",
        "Christmas tree",
        "Christmas pudding",
        "Santa’s hat",
        "Fireplace",
        "Gingerbread house",
        "Santa Claus",
        "Elf",
        "Snowman",
        "Sleigh",
        "Reindeer",
        "Santa’s sack",
        "Christmas card",
        "Chimney",
        "Menorah (Hanukkah)",
        "Snowflake",
        "Bible",
        "Candy",
        "Easter egg",
        "Hot-cross bun",
        "Chocolate",
        "Chick",
        "Daffodil",
        "Tulip",
        "Crucifixion",
        "Resurrection",
        "Cross",
        "Easter bunny",
        "Easter basket",
        "Lamb",
        "Crown of thorns",
        "Pattern",
        "Bat",
        "Black cat",
        "Devil",
        "Mummy",
        "Haunted house",
        "Cemetery",
        "Ghost",
        "Jack-o’Lantern",
        "Cauldron",
        "Candy bag",
        "Costume",
        "Witch",
        "Witch hat",
        "Candy",
        "Owl",
        "Skull",
        "Tombstone",
        "Witch’s broom",
        "Spider web",
        "Skeleton",
        "Spider",
        "Fireworks",
        "Countdown",
        "Party hat",
        "Firecracker",
        "Champagne",
        "Confetti",
        "Mask",
        "Hourglass",
        "Balloon",
        "Party favor",
        "Streamer",
        "Postcard",
        "Sun",
        "Beach ball",
        "Sand toy",
        "Coconut palm",
        "Beach",
        "Deck chair",
        "Sandcastle",
        "Beach towel",
        "Beach vendor",
        "Bikini",
        "Swim trunks",
        "Visitor",
        "Beach umbrella",
        "Coconut",
        "Goggles",
        "Flip flops",
        "Hat",
        "Float",
        "Sunglasses",
        "Sun cream",
        "Pool",
        "Swimsuit",
        "Surfboard",
        "Canoe",
        "Church",
        "Wedding bell",
        "Champagne",
        "Bouquet",
        "Honeymoon",
        "Wedding cake",
        "Engagement ring",
        "Confetti",
        "Invitation",
        "Veil",
        "Wedding dress",
        "Bride",
        "Groom",
        "Bridesmaid",
        "Best man",
        "Priest/ Minister",
        "Musician",
        "Flower girl",
        "Lover",
        "Cupid",
        "Arrow",
        "Chocolate",
        "Teddy bear",
        "Gift",
        "Perfume",
        "Candy",
        "Balloon",
        "Card",
        "Ring",
        "Bouquet",
        "Halloween",
        "Christmas",
    )

    fun getTheme(): String {
        val randomNumber: Int = Random.nextInt(0, themes.size)
        return themes[randomNumber]
    }
}